### ISSUE TITLE
4.0 roadmap

### ISSUE THREAD

**Issue by andrewvk** [rsdn/CodeJam#128]
### Planned 4.0 changes:
**4.0 is breaking changes release!**
* Nullable reference type markup in all types (there shouldn't be a single warning when building it). Operator ! should be avoided as much as possible
* Remove old NotNull/CanBeNull R# attributes (to avoid double work on markup and conflicts with new NotNull attribute with different meaning)
* Remove targets: .NET FW 2.0 as very outdated, .NET Standard older than 2.0 as rarely used, .NET Core older than 3.1, as deprecated by Microsoft and produces warnings when building with MSBuild 16.8+.
* Remove all API marked in 3.X as Obsolete
* Mark all rarely used APIs as Obsolete (remove in 5.0)
* Use C# 9 features

@NN--- , @ig-sinicyn

**Comment by andrewvk** [comment]
For NRT, the most of attention should be paid to the markup of assertions, as they are the main obstacle to the use of CJ in projects with NRT.

**Comment by NN---** [comment]
.NET 3.5 is still used in the world since Windows 7 has it, therefore we do need supporting it.

Actually supporting .NET 2.0 is not a hard task if you have 3.5 support.
The main difference is lack of Expression and related classes.

Cannot say the same for .NET Standard and .NET Core prior 2.0, it was not so easy :)

I wonder whether we can get statistics for different .NET versions usage.

**Comment by andrewvk** [comment]
Supporting old targets is bad not so much additional work as slowing down analysis, building and tests.

**Comment by NN---** [comment]
Understandable.
3.5 is still used in many places, so it must be preserved.
I agree that FW 2.0, .NET Core < 2.0 and .NET Standard < 2.0 are really rare today and have enough problems to stop supporting them.

**Comment by NN---** [comment]
#129

**Comment by andrewvk** [comment]
#130

**Comment by NN---** [comment]
There is linked pull request for this.

> #130
